###
### generic GNU make Makefile for .tex -> .pdf.
### ransford at cs.washington.edu
###   http://github.com/ransford/pdflatex-makefile
###
### Recommended usage:
###   1. echo 'include Makefile.include' > Makefile
###   2. Optional: Edit the Makefile to override $(TARGET)
###      and anything else (e.g., PDFVIEWER, AFTERALL)
###
### Final result:
###   % cat Makefile
###   TARGET=mypaper
###   PDFVIEWER=open -a 'Adobe Acrobat Professional'
### AFTERALL=
###   include Makefile.include
###
###   mypostprocessingstep:
###           # do something...
###

PDFLATEX	?= pdflatex -halt-on-error -file-line-error
BIBTEX		?= bibtex

ifneq ($(QUIET),)
PDFLATEX	+= -interaction=batchmode
ERRFILTER	:= > /dev/null || (egrep ':[[:digit:]]+:' *.log && false)
BIBTEX		+= -terse
else
PDFLATEX	+= -interaction=nonstopmode
ERRFILTER=
endif

## Action for 'make view'
OS=$(shell uname -s)
ifeq ($(OS),Darwin)
PDFVIEWER	?= open
else
PDFVIEWER	?= xdg-open
endif

## Name of the target file, minus .pdf: e.g., TARGET=mypaper causes this
## Makefile to turn mypaper.tex into mypaper.pdf.
TARGETS += $(TARGET)
TEXTARGETS = $(TARGETS:=.tex)
PDFTARGETS = $(TARGETS:=.pdf)
AUXFILES   = $(TARGETS:=.aux)
LOGFILES   = $(TARGETS:=.log)

## If $(TARGET).tex refers to .bib files like \bibliography{foo,bar}, then
## $(BIBFILES) will contain foo.bib and bar.bib, and both files will be added as
## dependencies to $(PDFTARGETS).
## Effect: updating a .bib file will trigger re-typesetting.
BIBFILES = $(patsubst %,%.bib,\
		$(shell grep '^[^%]*\\bibliography{' $(TEXTARGETS) | \
			grep -o '\\bibliography{[^}]\+}' | \
			sed -e 's/^[^%]*\\bibliography{\([^}]*\)}.*/\1/' \
			    -e 's/, */ /g'))

## Add \input'ed or \include'd files to $(PDFTARGETS) dependencies,
## ebenso Betriebsanweisungen aus \BAinhalt{...} und \BAseite[...]{...}.
INCLUDEDTEX = $(patsubst %,%.tex,\
		$(shell grep '^[^%]*\\\(input\|include\|BAinhalt\|BAseite\)\(\[[^]]*\]\)\{0,1\}{' $(TEXTARGETS) | \
			grep -o '\\\(input\|include\|BAinhalt\|BAseite\)\(\[[^]]*\]\)\{0,1\}{[^}]\+}' | \
			sed -e 's/^.*{\([^}]*\)}.*/\1/'))

AUXFILES += $(INCLUDEDTEX:.tex=.aux)

## grab a version number from the repository (if any) that stores this.
## * REVISION is the current revision number (short form, for inclusion in text)
## * VCSTURD is a file that gets touched after a repo update
SPACE = $(empty) $(empty)
ifeq ($(shell git status >/dev/null 2>&1 && echo USING_GIT),USING_GIT)
  ifeq ($(shell git svn info >/dev/null 2>&1 && echo USING_GIT_SVN),USING_GIT_SVN)
    # git-svn
    REVISION := $(shell git svn find-rev git-svn)
    VCSTURD := $(subst $(SPACE),\ ,$(shell git rev-parse --show-toplevel)/.git/refs/remotes/git-svn)
  else
    # plain git
    REVISION := $(shell git rev-parse --short HEAD)
    # Name des Repositorys für die Lizenzzeile, z.B. lasercutter-einweisung
    REPOSITORY := $(shell basename -s .git "$$(git remote get-url origin 2>/dev/null || git rev-parse --show-toplevel)")
    GIT_BRANCH := $(shell git symbolic-ref HEAD 2>/dev/null)
    VCSTURD := $(subst $(SPACE),\ ,$(shell git rev-parse --show-toplevel)/.git/$(GIT_BRANCH))
  endif
else ifeq ($(shell hg root >/dev/null 2>&1 && echo USING_HG),USING_HG)
  # mercurial
  REVISION := $(shell hg id -i)
  VCSTURD := $(subst $(SPACE),\ ,$(shell hg root)/.hg/dirstate)
else ifneq ($(wildcard .svn/entries),)
  # subversion
  REVISION := $(subst :,-,$(shell svnversion -n))
  VCSTURD := .svn/entries
endif

# .PHONY names all targets that aren't filenames
.PHONY: all clean pdf view snapshot distill distclean clean-output copy-output

all: pdf copy-output $(AFTERALL)

pdf: $(PDFTARGETS)

view: $(PDFTARGETS)
	$(PDFVIEWER) $(PDFTARGETS)

# define a \Revision{} command you can include in your document's preamble.
# especially useful with e.g. draftfooter.sty or fancyhdr.
# usage: \input{revision}
#        ... \Revision{}
ifneq ($(REVISION),)
REVDEPS += revision.tex
revision.tex: $(VCSTURD)
	/bin/echo '\newcommand{\Revision}'"{$(REVISION)}" > $@
ifneq ($(REPOSITORY),)
	/bin/echo '\newcommand{\Repository}'"{$(REPOSITORY)}" >> $@
endif
AUXFILES += revision.aux
endif

# Versionsnummer für die Fußzeile (\Version in version.tex).
# Standard: Datum des letzten Commits (JJJJ.MM.TT), bei nicht committeten
# Änderungen mit "-entwurf". Überschreiben mit "make VERSION=...".
# Ohne git und ohne VERSION steht wie bisher das Datum in der Fußzeile.
ifeq ($(VERSION),)
ifeq ($(shell git status >/dev/null 2>&1 && echo USING_GIT),USING_GIT)
VERSION := $(shell TZ=Europe/Berlin git log -1 --format=%cd --date=format-local:%Y.%m.%d 2>/dev/null)
ifneq ($(VERSION),)
ifneq ($(shell git status --porcelain --untracked-files=no 2>/dev/null),)
VERSION := $(VERSION)-entwurf
endif
endif
endif
endif

.PHONY: version FORCE
FORCE:

# Version ausgeben, z.B. für die GitHub Action: make -s version
version:
	@echo $(VERSION)

ifneq ($(VERSION),)
REVDEPS += version.tex
# nur neu schreiben, wenn sich die Version ändert, sonst würde jedes
# "make" alle PDFs neu bauen
version.tex: FORCE
	@/bin/echo '\newcommand{\Version}'"{$(VERSION)}" > $@.neu
	@if cmp -s $@.neu $@; then rm $@.neu; else mv $@.neu $@; fi
endif

# Betriebsanweisungen: Eine BA ist aktiv, wenn ein Dokument in TARGET sie mit
# \BAinhalt{datei} als eigenes PDF baut. ba-aktiv.tex listet die aktiven BAs,
# \BAseite{datei} in der Einweisung bindet nur diese ein. Eine auskommentierte
# Zeile "TARGET += Betriebsanweisung_..." im Makefile schaltet die BA also als
# eigenes PDF und in der Einweisung ab.
BASEITEN := $(shell grep -l '^[^%]*\\BAseite' $(TEXTARGETS) 2>/dev/null)
ifneq ($(BASEITEN),)
BAAKTIV := $(shell grep -h '^[^%]*\\BAinhalt{' $(TEXTARGETS) 2>/dev/null | \
		sed -e 's/^.*\\BAinhalt{\([^}]*\)}.*/\1/')
REVDEPS += ba-aktiv.tex
# nur neu schreiben, wenn sich die Liste ändert (wie version.tex)
ba-aktiv.tex: FORCE
	@{ echo '% erzeugt von make: Betriebsanweisungen, die gebaut werden'; \
		for ba in $(BAAKTIV); do printf '\\BAaktiv{%s}\n' "$$ba"; done; } > $@.neu
	@if cmp -s $@.neu $@; then rm $@.neu; else mv $@.neu $@; fi
endif

# to generate aux but not pdf from pdflatex, use -draftmode
.INTERMEDIATE: $(AUXFILES)
%.aux: %.tex $(REVDEPS)
	$(PDFLATEX) -draftmode $* $(ERRFILTER)

# introduce BibTeX dependency if we found a \bibliography
ifneq ($(strip $(BIBFILES)),)
BIBDEPS = %.bbl
%.bbl: %.aux $(BIBFILES)
	$(BIBTEX) $*
endif

$(PDFTARGETS): %.pdf: %.tex %.aux $(BIBDEPS) $(INCLUDEDTEX) $(REVDEPS)
	$(PDFLATEX) $* $(ERRFILTER)
ifneq ($(strip $(BIBFILES)),)
	@if grep -q "undefined references" $*.log; then \
		$(BIBTEX) $* && $(PDFLATEX) $* $(ERRFILTER); fi
endif
	@while grep -q "Rerun to" $*.log; do \
		$(PDFLATEX) $* $(ERRFILTER); done

DRAFTS := $(PDFTARGETS:.pdf=-$(REVISION).pdf)
$(DRAFTS): %-$(REVISION).pdf: %.pdf
	cp $< $@
snapshot: $(DRAFTS)

%.distilled.pdf: %.pdf
	gs -q -dSAFER -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$@ \
		-dCompatibilityLevel=1.5 -dPDFSETTINGS=/prepress -c .setpdfwrite -f $<
	exiftool -overwrite_original -Title="" -Creator="" -CreatorTool="" $@

distill: $(PDFTARGETS:.pdf=.distilled.pdf)

distclean: clean
	$(RM) $(PDFTARGETS) $(PDFTARGETS:.pdf=.distilled.pdf) $(EXTRADISTCLEAN)

clean: clean-output
	$(RM) $(foreach T,$(TARGETS), \
		$(T).out $(T).blg $(T).bbl \
		$(T).lof $(T).lot $(T).toc $(T).idx \
		$(T).nav $(T).snm) \
		$(REVDEPS) version.tex version.tex.neu ba-aktiv.tex ba-aktiv.tex.neu $(AUXFILES) $(LOGFILES) \
		$(EXTRACLEAN)

# output/ enthält genau die PDFs aus TARGET, alte (z.B. einer abgeschalteten BA) fliegen raus
copy-output: pdf
	mkdir -p output
	find output/ -name "*.pdf" -delete
	cp $(PDFTARGETS) output/

clean-output:
	mkdir -p output
	find output/ -name "*.pdf" -delete
	
