TARGET  = my_tex_main_filename__TODO__changeme
# Betriebsanweisung, standardmäßig aus. Einkommentieren: BA wird als eigenes PDF
# und als Seite in der Einweisung gebaut.
#TARGET += Betriebsanweisung_Geraet
include fablab-document/Makefile.include
